version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build: .
    command: python celery_worker.py
    env_file:
      - .env
    depends_on:
      - redis
